In [2]:
#이미 정행진 행렬들에 대하여 알아보기(Ref BJ)

import numpy as np
A = np.zeros((2,3)) # 행렬의 크기, 사이즈
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
A.dtype  #64비트 실수 타입

dtype('float64')

In [4]:
B = np.ones((2,3))
print(B)
B.dtype

[[1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [5]:
print(A+B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [123]:
I= np.eye(3)  # eyp는 identity matrix의 I
print(I)
np.multiply(3, I) # scalar multiple of I by scalar 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [129]:
J = np.ones((3,3))
print(J)
print(np.dot(J,J)) # 첫 번째 방법 for 행렬의 곱
print(np.dot(I,J))
print(J.dot(J)) # 두 번째 방법 for 행렬의 곱

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [47]:
# resize는 뷰는 생성하지 않고 바로 형태를 바꿈
A = np.arange(10)

print("A=", A)

A= [0 1 2 3 4 5 6 7 8 9]


In [48]:
A.resize(2,5)  # 2*5 행렬로 재배열

In [49]:
print("A=", A) # 새로운 A로 변함

A= [[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
A = np.array([[1, 3],[5, 7]])
B = np.array([[2,4], [6,8]])
print(A)
print(B)

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]


In [6]:
 # 세로로 붙이기
C = np.vstack((A,B))  # vertcal 
print(C)
C.shape

[[1 3]
 [5 7]
 [2 4]
 [6 8]]


(4, 2)

In [63]:
 # 가로로 붙이기
C = np.hstack((A,B)) #horizontal
print(C)
C.shape

[[1 3 2 4]
 [5 7 6 8]]


(2, 4)

In [65]:
# concatenate 함수로 vstack과 hstack을 작성할 수 있음
import numpy as np

A = np.array([[1,3], [5,7]])
B = np.array([[2,4], [6,8]])

C = np.concatenate((A,B), axis =0) # 열방항으로, vstack
print(C)
print()
D =  np.concatenate((A,B), axis =1) # 행방항으로, hstack
print(D)

[[1 3]
 [5 7]
 [2 4]
 [6 8]]

[[1 3 2 4]
 [5 7 6 8]]


In [68]:
# hsplit를 이용하여 배열 분할하기, 왼쪽에서부터 읽음

C = np.arange(15).reshape(3,5)
print(C)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [69]:
c = np.hsplit(C, (2,4))  # 중간 2~3열을 기준으로 좌, 우 분할

In [70]:
c[0]  # C[:, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [71]:
c[1]  # C[:, 2:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [72]:
c[2]  # C[:, 3:4]

array([[ 4],
       [ 9],
       [14]])

In [73]:
d = np.hsplit(C, 5)  

In [74]:
d[0]

array([[ 0],
       [ 5],
       [10]])

In [75]:
d[4]

array([[ 4],
       [ 9],
       [14]])

In [80]:
# vsplit를 이용하여 배열 분할하기, 위에서부터 읽음

C = np.arange(15).reshape(5,3)
print(C)
c_1 = np.vsplit(C, (1,2))
print()
print(c_1[0])
print()
print(c_1[1])
print()
print(c_1[2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[0 1 2]]

[[3 4 5]]

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [82]:
# 인덱싱(indexing)하기

import numpy as np

A = np.arange(1,15, 2)
print(A)

[ 1  3  5  7  9 11 13]


In [83]:
A.shape

(7,)

In [84]:
A[0]  # index 0이 첫번째임

1

In [85]:
A[1]

3

In [86]:
A[-1]  #맨 뒤에서 첫 번째

13

In [87]:
A[-2]  #맨 뒤에서 두번째

11

In [93]:
# 인덱싱(indexing)하기

import numpy as np

A = np.arange(0, 40, 2).reshape(4,5)
print(A)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [96]:
A.ndim  # 2차원 배열이라는 뜻

2

In [97]:
print(A[0,0])
print(A[1,1])

0
12


In [99]:
print(A[0])  #첫 번째 행

[0 2 4 6 8]


In [100]:
for row in A:
    print(row)

[0 2 4 6 8]
[10 12 14 16 18]
[20 22 24 26 28]
[30 32 34 36 38]


In [102]:
# A의 전치행렬 transpose
A.T


array([[ 0, 10, 20, 30],
       [ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38]])

In [103]:
for column in A.T:   # A의 column을 생성함
    print(column)

[ 0 10 20 30]
[ 2 12 22 32]
[ 4 14 24 34]
[ 6 16 26 36]
[ 8 18 28 38]


In [104]:
#행렬 A의 원소를 0행부터 생성
for a in A.flat:
    print(a)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38


In [105]:
# 슬라이싱

A = np.arange(1, 10, 2)
print(A)

[1 3 5 7 9]


In [106]:
A[0:2]  # 0부터 1까지

array([1, 3])

In [107]:
A[:2] # 0생략 가능

array([1, 3])

In [108]:
A[:] # 전체 생성

array([1, 3, 5, 7, 9])

In [109]:
A[::2]  # 두 칸씩 건너뛰기

array([1, 5, 9])

In [110]:
A[: -2]  # 뒤에서 2칸을 제외하기

array([1, 3, 5])

In [111]:
A[-2 :] # 마지막 2개만 선택

array([7, 9])

In [112]:
A

array([1, 3, 5, 7, 9])

In [113]:
# 행렬 인덱싱

import numpy as np

A = np.arange(0, 40, 2).reshape(4,5)
print(A)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [114]:
A[0]

array([0, 2, 4, 6, 8])

In [115]:
A[:, 0]  # 모든 행과 0번째 열, 즉 0번째 열

array([ 0, 10, 20, 30])

In [117]:
A[0,:]  # 0번째 행과 모든 열, 즉 0번째 행

array([0, 2, 4, 6, 8])

In [119]:
A[:2, :2] =0

In [120]:
A

array([[ 0,  0,  4,  6,  8],
       [ 0,  0, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [1]:
#실습 for 영행렬, 1로 이루어진 행렬, 3으로 이루어진 행렬 
import numpy as np

a = np.zeros((2,3)) # 행렬 사이즈가 2 * 3
print("a=", a)

a= [[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
a.T  #전치행렬. 3 * 2 행렬

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
c = np.full((2,3), 3) # 3으로 이루어진 2 by 3 행렬
print(c)

[[3 3 3]
 [3 3 3]]


In [5]:
d = np.eye(3) # 3차 단위행렬 Identity matrix.
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 가우스-조단 소거법 이용하여 
#  2x + 2y + 4z = 18
#   x + 3y + 2z = 13
#  3x + y + 3z = 14
# 풀기

In [7]:
# 행렬 A  출력하기
import numpy as np

def pprint(msg, A):  # 함수 pprint
    print("---", msg, "---")
    (n,m) = A.shape  # A 행렬의 사이는?
    for i in range (0,n):   # n=3이면 range (0,3)의미는 1,2,3번째 행
        line = ""
        for j in range(0, m):
            line += "{0:.2f}".format(A[i,j]) + "\t"  # \t는 '탭'주기
            if j == n-1:
                line += "|"
        print(line)
    print("")

    
# Test
A =np.array([[1,1], [1,2]]) 
print("A=", A)
pprint("Test", A )    

A= [[1 1]
 [1 2]]
--- Test ---
1.00	1.00	|
1.00	2.00	|



In [8]:
# 가우스 소거법 함수
def gauss(A):
    (n,m) = A.shape
    
    
    for i in range(0,n):
        # i번째 열에서 절댓값이 최대인 성분의 행 선택
        maxEl = abs(A[i,i])
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k,i]) > maxEl:
                maxEL =abs(A[k,i])
                maxRow = k
        
        # 현재 i번째 행과 최댓값을 갖는 행 maxRow의 교환
        
        for k in range(i, m):
            tmp = A[maxRow, k]
            A[maxRow, k] = A[i,k]
            A[i,k] = tmp
            
        #피벗을 1로 만들기
        piv = A[i,i]
        for k in range(i, m):
            A[i,k] = A[i,k]/piv
        
        #현재 i번째 열의 i번째 행을 제외한 모든 성분을 0으로 만들기
        for k in range(0, n):
            if k != i:
                c = A[k,i]/A[i,i]
                for j in range(i,m):
                    if i == j:
                        A[k,j] = 0
                    else:
                        A[k,j] = A[k,j] -c*A[i,j]  # replace kth row

        pprint(str(i+1)+ "번째 반복", A)     #중간과정 출력

    # Ax=b의 해 반환    
    x = np.zeros(n)
    for i in range(0,n):
        x[i] = A[i,n]
    return x

# Augmented matrix(첨가행렬)
A = np.array([[2., 2., 4., 18.], [1., 3., 2., 13.], [3., 1., 3., 14.]])
pprint("행렬로 표현", A) #첨가행렬
x = gauss(A)  #가우스 소거법 적용

--- 행렬로 표현 ---
2.00	2.00	4.00	|18.00	
1.00	3.00	2.00	|13.00	
3.00	1.00	3.00	|14.00	

--- 1번째 반복 ---
1.00	0.33	1.00	|4.67	
0.00	2.67	1.00	|8.33	
0.00	1.33	2.00	|8.67	

--- 2번째 반복 ---
1.00	0.00	0.88	|3.63	
0.00	1.00	0.38	|3.12	
0.00	0.00	1.50	|4.50	

--- 3번째 반복 ---
1.00	0.00	0.00	|1.00	
0.00	1.00	0.00	|2.00	
0.00	0.00	1.00	|3.00	



In [9]:
#출력 생성
(n,m) = A.shape
line = "해:\t"
for i in range(0,n):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)    

해:	1.00	2.00	3.00	


In [41]:
# Another example
B = np.array([[0., 2., 1., 1.], [2., 4., -2., 2.], [3., 5., -5., 1.]])
pprint("행렬로 표현", B) #첨가행렬
x = gauss(B)  #가우스 소거법 적용

#출력 생성
(n,m) = B.shape
line = "해:\t"
for i in range(0,n):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)    

--- 행렬로 표현 ---
0.00	2.00	1.00	|1.00	
2.00	4.00	-2.00	|2.00	
3.00	5.00	-5.00	|1.00	

--- 1번째 반복 ---
1.00	1.67	-1.67	|0.33	
0.00	0.67	1.33	|1.33	
0.00	2.00	1.00	|1.00	

--- 2번째 반복 ---
1.00	0.00	-2.50	|-0.50	
0.00	1.00	0.50	|0.50	
0.00	0.00	1.00	|1.00	

--- 3번째 반복 ---
1.00	0.00	0.00	|2.00	
0.00	1.00	0.00	|0.00	
0.00	0.00	1.00	|1.00	

해:	2.00	0.00	1.00	


In [46]:
# Another example
C = np.array([[1., -5., 4., -3.], [2., -7., 3., -2.], [-2., 1., 7., -1.]])
pprint("행렬로 표현", C) #첨가행렬
x = gauss(C)  #가우스 소거법 적용

#출력 생성
(n,m) = C.shape
line = "해:\t"
for i in range(0,n):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)    

--- 행렬로 표현 ---
1.00	-5.00	4.00	|-3.00	
2.00	-7.00	3.00	|-2.00	
-2.00	1.00	7.00	|-1.00	

--- 1번째 반복 ---
1.00	-0.50	-3.50	|0.50	
0.00	-6.00	10.00	|-3.00	
0.00	-4.50	7.50	|-3.50	

--- 2번째 반복 ---
1.00	0.00	-4.33	|0.75	
0.00	1.00	-1.67	|0.50	
0.00	0.00	0.00	|-1.25	

--- 3번째 반복 ---
1.00	0.00	0.00	|nan	
0.00	1.00	0.00	|nan	
0.00	0.00	nan	|-inf	

해:	nan	nan	-inf	


C:\Users\CICAGO_Lab2\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in double_scalars
C:\Users\CICAGO_Lab2\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:25: RuntimeWarning: divide by zero encountered in double_scalars


In [43]:
# Another example
D = np.array([[3., 6., -3., 6.], [2., 7., 4., 28.], [2., -6., 4., 2.]])
pprint("행렬로 표현", D) #첨가행렬
x = gauss(D)  #가우스 소거법 적용

#출력 생성
(n,m) = D.shape
line = "해:\t"
for i in range(0,n):
    line += "{0:.2f}".format(x[i]) + "\t"
print(line)    

--- 행렬로 표현 ---
3.00	6.00	-3.00	|6.00	
2.00	7.00	4.00	|28.00	
2.00	-6.00	4.00	|2.00	

--- 1번째 반복 ---
1.00	2.00	-1.00	|2.00	
0.00	3.00	6.00	|24.00	
0.00	-10.00	6.00	|-2.00	

--- 2번째 반복 ---
1.00	0.00	0.20	|1.60	
0.00	1.00	-0.60	|0.20	
0.00	0.00	7.80	|23.40	

--- 3번째 반복 ---
1.00	0.00	0.00	|1.00	
0.00	1.00	0.00	|2.00	
0.00	0.00	1.00	|3.00	

해:	1.00	2.00	3.00	
